[tool.basedpyright]
reportAny = false
reportExplicitAny = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportImplicitStringConcatenation = false
reportUnnecessaryComparison = false

[tool.black]
line-length = 80
